language: node_js
branches:
 only: 
   - master
   - /^greenkeeper/.*$/
cache:
 yarn: true
 directories:
  - node_modules
notifications:
 email: false
node_js:
 - node
jobs:
 include:
  - script: npm run test:prod
  - stage: Build
    script: npm run build
after_success:
 - npm run report
 - npm run clean
