language: node_js
branches:
 only: 
   - master
   - /^greenkeeper/.*$/
notifications:
 email: false
node_js:
 - 8
jobs:
 include:
  - stage: Test
    script: npm run test:prod
  - stage: Build
    script: npm run build
  - stage: Release
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script:
        - npm run build
        - npx semantic-release
after_success:
 - npm run report
 - npm run clean
